# Site settings
title: Sophie Starck
description: 'Contact Information'
url: 'http://starcksophie.github.io/'
# baseurl: '/cv'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Sophie Starck'
  email: sophiestarck1@gmail.com
  twitter_username: StarckSophie
  facebook_username: Sophie Starck
  github_username:  starcksophie
  linkedin_username:  Sophie Starck

# defaults:
#   -
#     scope:
#       path: ''
#       type: 'posts'
#     values:
#         layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false


exclude: ['Gemfile', 'Gemfile.lock']
